version: '3.4'

services:
  frontend:
    image: acatanzaro/frontend:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DataServiceEndPoint=http://backend:80
    secrets:
      - app_frontend_secret_sample
    configs:
      - app_sample_config
      - app_sample_config_value
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - backend
    deploy:
      mode: replicated
      replicas: 2
    hostname: "frontend-{{.Node.Hostname}}-{{.Task.Slot}}"

  backend:
    image: acatanzaro/backend:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    secrets:
      - app_backend_secret_sample
    configs:
      - app_sample_config
      - app_sample_config_value
    depends_on:
      - sqldata
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 4
    hostname: "backend-{{.Node.Hostname}}-{{.Task.Slot}}"

  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=6k#thL^qQdVPWdg2eNHWfg2aDcHZeWVE&Mruh*8t
      - ACCEPT_EULA=Y
    secrets:
      - app_sqldata_secret_sample
    configs:
      - app_sample_config
      - app_sample_config_value
    ports:
      - "1433:1433"
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == node5
    hostname: "sqldata"

networks:
  app-network:

secrets:
  app_frontend_secret_sample:
    external: true
  app_backend_secret_sample:
    external: true
  app_sqldata_secret_sample:
    external: true

configs:
  app_sample_config_value:
    external: true
  app_sample_config:
    external: true