version: '3.4'

services:
  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DataServiceEndPoint=http://backend:80
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

networks:
  app-network:

